name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3, 3.2, 3.1, ruby-head]
        rails: ['7.2.0', '7.1.0', '7.0.0', main]
        exclude:
          - ruby: ruby-head
            rails: '7.0.0'
          - ruby: 3.1
            rails: main

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake
